* [32mdev[m
  feature/UC1-FeetEquality[m
  feature/UC10-GenericQuantity[m
  feature/UC11-VolumeEquality[m
  feature/UC12-SubtractionDivision[m
  feature/UC13-CentralizedArithmetic[m
  feature/UC14-TemperatureMeasurement[m
  feature/UC15-N-Tier[m
  feature/UC16-JDBCPersistence[m
  feature/UC17-SpringBackend[m
  feature/UC18/-SpringSecurity[m
  feature/UC2-InchEquality[m
  feature/UC21-MicroservicesArchitecture[m
  feature/UC3-GenericLength[m
  feature/UC4-YardEquality[m
  feature/UC5-UnitConversion[m
  feature/UC6-UnitAddition[m
  feature/UC7-TargetUnitAddition[m
  feature/UC8-StandaloneUnit[m
  feature/UC9-WeightMeasurement[m
  main[m
